### ISSUE TITLE
Special chars on custom variables not working

### ISSUE THREAD

**Issue by barneyemma** [Mikesch-mp/icingaweb2-module-grafana#239] opened 2020-02-26 06:23 UTC
Hey!
I have an icinga service that has a custom variable with special chars ("=", ")", "}" etc...)
The problem is - when sending this variable to grafana only the chars before the "=" are being sent to the dashboard.
For example - the variable is:
max(kube_deployment_spec_replicas{deployment="blabla"}) without (instance, pod)

and what is passed on to grafana is:
max(kube_deployment_spec_replicas{deployment

Is there a solution for this problem? Or can I manually escape chars?
P.S - adding backslash before those chars doesn't help - since backslash is being transformed into "_".

## Expected Behavior

Pass the entire content of the variable to grafana

## Current Behavior

Only the chars before the "=" are being sent.

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.6
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): 2.10.5-1
* Operating System and version: Centos7.5

**Comment by Mikesch-mp** [comment] 2020-03-11 16:33
Duplicate of #238

**Closed by Mikesch-mp** 2020-03-11 16:33 UTC
Labels: duplicate
