### ISSUE TITLE
Feature request: All panels

### ISSUE THREAD

**Issue by p0nt** [Mikesch-mp/icingaweb2-module-grafana#42] opened 2017-05-01 07:50 UTC
Would love to see a wildcard possibility with the "PanelId(s)" option.

For example I have a dashboard with the following templatings:

$host = SHOW TAG VALUES FROM "filesystems" WITH KEY = "hostname"
$filesystem = SHOW TAG VALUES FROM "filesystems" WITH KEY = "metric" WHERE hostname =~ /$host/

Which means for each host there is a different number of panels available for this dashboard, and because its hardcoded now I can not use the grafana module for this specific dashboard.

If a wildcard (*) option would exist, it would check with grafana how many panels there are and just show them all.

Currently I have a very ugly way with my hacked grafana graph version to loop through the dashboard this way:

`/usr/bin/curl http://icinga:3000/api/dashboards/db/icinga2-filesystems 2> /dev/null | python -m json.tool | sed -n -e '/panels/,$p'| grep '"id"' | grep -o [0-9]*`

This will list the panel numbers:

`root@icinga:/# /usr/bin/curl http://icinga:3000/api/dashboards/db/icinga2-filesystems 2> /dev/null | python -m json.tool | sed -n -e '/panels/,$p'| grep '"id"' | grep -o [0-9]*`

1
2
3
4
5
6
7
8

Maybe you are able to find a better and easier way to query grafana for this information?

**Comment by p0nt** [comment] 2017-05-01 07:55
btw, the reason this gives trouble is if a host has only 1 panel but the grafana settings want panels 1,2,3,4 it will query grafana for panels that dont exist which will result in a unresponsive webinterface untill grafana gives error and show no graph.

**Comment by p0nt** [comment] 2017-05-01 08:20
I think this is not possible because the grafana curl api does not allow any variables in the url.

works: http://icinga:3000/api/dashboards/db/icinga2-filesystems

does not work: http://icinga:3000/api/dashboards/db/icinga2-filesystems?var-host=nfs02&var-filesystem=All

I will have a look if anything else is possible

**Comment by Mikesch-mp** [comment] 2017-05-16 19:29
Hi,

with v1.2.0 there will be a link thats leads to a page with all service graphs of a host. 

Best regards,

Carsten

**Comment by p0nt** [comment] 2017-05-16 20:15
Sounds great, looking forward to see how you did it!

Keep up the good work!

**Comment by Mikesch-mp** [comment] 2017-05-21 07:10
Duplicate of #30

**Comment by p0nt** [comment] 2017-05-22 05:53
not duplicate btw, this would be a feature to show all graphs for a certain dashboard not a host.

2 different features

**Comment by Mikesch-mp** [comment] 2017-05-22 06:00
HI,
yeah i know. looks like i closed the wrong one. sorry

**Comment by Mikesch-mp** [comment] 2017-05-22 06:02
i Know, but as long we cant get all panels via api from Grafana, there will be no solution for this issue. Maybe you open a feature request at the Grafana repository?

**Comment by p0nt** [comment] 2017-05-22 06:25
yes that is true, I will have a look at it!

**Comment by p0nt** [comment] 2017-05-22 06:29
https://github.com/grafana/grafana/issues/8434

**Comment by p0nt** [comment] 2017-05-22 08:42
got the following answer:

The templating queries & variables and evaluation of repeated panels & rows is all done in the browser, so the api cannot return the info you want.

**Comment by Mikesch-mp** [comment] 2017-05-22 08:49
Matches what i expected. So i can only give you the featrue to show all services of a host on one page.

**Comment by lesinigo** [comment] 2017-05-22 09:04
Not sure if it is relevant here, but the actual query used to get possible variable values is done by grafana-server to its backend. Grafana is definitely able to give you a list of host and services, if you have them as tags in InfluxDB (or any other grafana backend that can manage templating queries.).

It is the interpolation of those results with the dashboard definition that's done in the browser (and gives you the number of rows and graphs and series in a graph, according to the various templating / repetition settings).

**Comment by p0nt** [comment] 2017-05-22 09:07
indeed, lets do that and close this issue!

@lesingo that was exactly what I was looking for, for example server01 has 1 filesystem and server02 has 2 filesystems.

server01 will have 1 panel
server02 will have 2 panels

When I give the filesystem service in the grafana module panels 1,2 it will also try to pull panel 2 for server01 which it shouldnt.

I thought it would be possible to use for example * and select all panels based on a variable in the url, but as stated by the grafana DEV in https://github.com/grafana/grafana/issues/8434 it is indeed not possible because its done in the browser and not on server side.

I guess this case can be closed, unfortunately. (I dont know how to solve this issue with current config)

**Comment by lesinigo** [comment] 2017-05-22 09:41
@p0nt I am not sure if I understood your original question correctly.

If you want one graph per service, with all the performance data on it, even if you don't know _how many_ performance data you get, that should be doable. As an example, think about [filesystem space from the disk check](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/plugin-check-commands#plugin-check-command-disk), which you don't know beforehand how many filesystem you will have. You can repeat the query in a single graph using the group by feature.

You can have a single graph with a query like this (InfluxDB example) `SELECT mean("value") FROM /^$measurement$/ WHERE "hostname" =~ /^$hostname$/ AND "metric" =~ /^$metric$/ AND $timeFilter GROUP BY time($__interval), "metric" fill(none)` (and then add `ALIAS BY $tag_metric`).
All the data you need to pass is already known to IcingaWeb2: hostname, check_command (measurement) and service (metric).

**Comment by p0nt** [comment] 2017-05-22 10:49
thank you for your help @lesinigo, actually I wanted a different panel for each filesystem so this would not solve the problem.

filesystems in 1 graph would be ok, but interface graphs with in/out metrics would not fix for that purpose.

**Comment by Caez83** [comment] 2017-06-26 13:24
I have a similar problem with some of graphs. 
For example, i'm using all_disks plugin with return every disk on the server (And some servers have not the same disks )

I have each value on perfdata
	Label	Value	
	/var	         296.49 GiB	
	/	         2.04 GiB

On grafana i've created a $disk variable for splitting graphs 

If it's not possible to have all the grafana panelids, it is possible to repeat a defined variable for each perfdata value ( if i have 5 disks i have 5 graphs ) ?
for example &disk=$perfdatalabel$ ?

**Comment by Mikesch-mp** [comment] 2017-06-26 15:49
@p0nt @Caez83 i have an idea to mark graphs as repeatable, but the have to be the only graph/panel in the dashboard to work. Then i could loop through panels = count(perfdata array). But i need to finish all panels for host first.

**Comment by Caez83** [comment] 2017-06-26 16:08
Thank you

**Comment by p0nt** [comment] 2017-06-26 19:10
Thanks from me 2!

**Comment by Mikesch-mp** [comment] 2017-08-12 21:22
Implemented with 777261f

**Closed by Mikesch-mp** 2017-08-12 21:22 UTC
Labels: enhancement

**Comment by dnsmichi** [comment] 2017-08-14 07:35
Screenshot for README.md? :)

**Comment by p0nt** [comment] 2017-08-15 05:26
I have just tested this, I can't seem to understand how this works.

Settings:
http://shot.xsnews.nl/stefan/dcef62f99ffd630b.png

How it looks:
http://shot.xsnews.nl/stefan/c25b791a01fb73fb.png

As you can see there is allot of white space around the 2 graphs.

What should I fill it at 'PanelId(s) *' to make this work?

**Comment by p0nt** [comment] 2017-08-15 05:29
I found it, there were only 2 graphs in the panel but for some reason they had id 2 and 3 which means he was showing id 0 and 1 also but they were non existant

**Comment by Mikesch-mp** [comment] 2017-08-15 17:44
@p0nt see the example dashboard to get an idea how this showld work.
For example you have a check thats has all disks at once in it, lets asume "c:\=50% d:\=50% e:\=60% f:\=55%" as the perfdata we get. You setup a dashboard where you get the metrics for that check with a template like 
```
SHOW TAG VALUES FROM /^disk$/ WITH KEY = "metric" where hostname =~ /^$hostname$/ and service =~ /^$service$/' 
``` 
and in you panel you have a query 
```
SELECT mean("value") FROM "disk" WHERE "hostname" =~ /^$hostname$/ AND "service" =~ /^$service$/ AND "metric" =~ /^$perf$/ AND $timeFilter GROUP BY time($interval), "metric" fill(none)
```

Now you can repeat the row or the panel for $perf. The module will then load all the panels that grafana will auto generate.

Pic before the auto repeat will hit:
![image](https://user-images.githubusercontent.com/6574967/29328173-e9ec596e-81f1-11e7-8482-f54958d29cd1.png)

And now with auto repeat

![image](https://user-images.githubusercontent.com/6574967/29328205-0f1d0ba2-81f2-11e7-9630-19108e7b1c6c.png)

This works no matter how many metrics are there.
