### ISSUE TITLE
Graphs for services without perfomance data collection after upgrade

### ISSUE THREAD

**Issue by killepitisch** [Mikesch-mp/icingaweb2-module-grafana#161] opened 2018-05-30 13:36 UTC
## Expected Behavior
No performance graphs rendered for services that have "enable_perfdata" set to "false".

## Current Behavior
Graphs are rendered for all services regardless whether performance data collection is enabled or disabled. "No data points" for services without collection of course.

## Context
The issue appeared after upgrading the Grafana module from v1.2.1 to v1.2.4. When switching back to v1.2.1 the behavior is as expected, again.

Maybe related to issue #111?

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.2.4
* Icinga Web 2 version and modules (System - About): 2.5.3
* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: SLES SP3
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification

config.ini:
[grafana]
host = "xxx:3000"
protocol = "http"
defaultdashboard = "icinga2-default"
defaultorgid = "1"
shadows = "0"
defaultdashboardstore = "db"
theme = "light"
datasource = "influxdb"
accessmode = "direct"
debug = "0"
height = "280"
width = "640"
enableLink = "yes"
usepublic = "no"
timerangeAll = "1w/w"
defaultdashboardpanelid = "1"
version = "0"
directrefresh = "no"

**Comment by Mikesch-mp** [comment] 2018-05-30 17:09
Yeah its exactly the same problem and i found a solution. Closing this issue as duplicate of #111

**Closed by Mikesch-mp** 2018-05-30 17:09 UTC
Labels: bug, duplicate
